### PR TITLE
New Input system and a better pause menu.

### PR DESCRIPTION
**Pull request by mfdavies**
Additionally:
- Various Bugfixes and updates
- Properly access the game manager
- Added a rebinding menu

### CODE REVIEW

**Review by AlexanderSalm — APPROVED** [review]
I did notice some bugs (that I dont think are big enough to prevent adding this, but maybe good to know), but this is pretty good work so far. I think being able to rebind controls is a really good addition!

The bugs I saw were:

- The first time I opened the rebind menu, it froze for like 10 seconds ish, but it hasn't happened since
- When clicking resume with left click bound as dash, the player will immediatly also dash
- There seems to be an issue with the font where some letters are missing characters and just become squares?
- Keybinds aren't saved between runs of the game (PlayerPrefs should make this pretty easy to add)

**Comment by mfdavies** [comment]
> I did notice some bugs (that I dont think are big enough to prevent adding this, but maybe good to know), but this is pretty good work so far. I think being able to rebind controls is a really good addition!
> 
> The bugs I saw were:
> 
> * The first time I opened the rebind menu, it froze for like 10 seconds ish, but it hasn't happened since
> * When clicking resume with left click bound as dash, the player will immediatly also dash
> * There seems to be an issue with the font where some letters are missing characters and just become squares?
> * Keybinds aren't saved between runs of the game (PlayerPrefs should make this pretty easy to add)

1 second let me double check something.

**Comment by mfdavies** [comment]
> * e first time I opened the rebind menu, it froze for like 10 seconds ish, but it hasn't happened since
> * When clicking resume with left click bound as dash, the player will immediatly also dash
> * There seems to be an issue with the font where some letters are missing characters and just become squares?
> * Keybinds aren't saved between runs of the game (Player

Would you mind double checking that you have the new input system installed?
- The freeze is weird (I dont have that issue). as long as it is a 1 time (ever) thing it may just be unity swapping input systems
- I know of the dashing bug and how to fix it. I will add it to the trello and fix it in a bit.
- Hmmm which characters are missing for you? they all work fine for me so that is very weird.
- I have fixed the issue with key binds not being saved. View the latest commit for details.

**Comment by AlexanderSalm** [comment]
image

Here is a screenshot of what I'm seeing for the fonts issue, it's weird that it's only happening to me. I've checked and I do have the new input system, and it's never frozen since so it was probably just a one off like you said.

**Comment by AlexanderSalm** [comment]
An update to this bug is that I'm also seeing these warnings
image

**Comment by mfdavies** [comment]
> An update to this bug is that I'm also seeing these warnings image

I'll merge it for now and we can deal with this issue later. All of that text is generated by unity itself

**Pull request merged**
