### PR TITLE
Implemented all types of platforms and made the naming scheme in files consistent

### PR DESCRIPTION
**Pull request by mfdavies**
Moving platforms are still buggy and will be fixed in the future.

### CODE REVIEW

**Comment by mfdavies** [comment]
Missing timed/switchable platforms but those will come in a future pr.

**Comment by mfdavies** [comment]
I rebound dash to "q" as I was missing it for some reason. It appears along the way the values for it were lost so it currently behaves weirdly

**Comment by ChesterLuna** [comment]
Im not sure how to drop down, for me it is only working when pressing down and jumping at the same time. What's the intended key?

**Comment by mfdavies** [comment]
> Im not sure how to drop down, for me it is only working when pressing down and jumping at the same time. What's the intended key?

I apologize, I should have mentioned that. Holding down and then pressing jump in the intended mechanic. If we would like to change it to a single button press I can.

**Review by ChesterLuna — APPROVED** [review]
Everything looks good. I realized that the Dash is not broken, you just changed the _dashtime so we can change it later.

**Pull request merged**
